services:

  postgres_backend:
    image: postgres:16
    container_name: postgres_backend
    environment:
      POSTGRES_DB: backend_db
      POSTGRES_USER: ${BACKEND_DB_USER}
      POSTGRES_PASSWORD: ${BACKEND_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_backend_data:/var/lib/postgresql/data

  postgres_keycloak:
    image: postgres:16
    container_name: postgres_keycloak
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres_keycloak:5432/keycloak_db
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    ports:
      - "8085:8080"
    command: start-dev
    depends_on:
      - postgres_keycloak


volumes:
  postgres_backend_data:
  postgres_keycloak_data:
